services:
  webserver:
    build: .
    networks:
    - webserver-network

  nginx:
    image: nginx:1.30
    ports:
    - '8080:8080'
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
    - webserver
    networks:
    - webserver-network

networks:
  webserver-network:
    driver: bridge